version: "3.8"
services:
  frontend:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 3000:3000
    image: frontend
    container_name: react_container
    command: npm start
  backend:
    image: backend
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - tracing.dotnet
